import React, { useState, useEffect } from 'react';
import { FileText, Download, Loader2, Clock, File } from 'lucide-react';
import * as api from '../../api/client';

const DOCUMENT_TYPE_LABELS = {
  'plan': 'Plan Document',
  'executive_report': 'Executive Report',
  'technical_report': 'Technical Report'
};

export default function DocumentHistory({ engagementId }) {
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadDocuments();
  }, [engagementId]);

  async function loadDocuments() {
    try {
      setLoading(true);
      const data = await api.getEngagementDocuments(engagementId);
      setDocuments(data || []);
    } catch (err) {
      setError('Failed to load documents');
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  async function handleDownload(document) {
    try {
      setDownloading(document.id);
      await api.downloadDocument(engagementId, document.id);
    } catch (err) {
      setError('Failed to download document');
    } finally {
      setDownloading(null);
    }
  }

  function formatFileSize(bytes) {
    if (!bytes) return 'Unknown size';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8">
        <Loader2 className="w-6 h-6 animate-spin text-purple-500" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div>
        <h3 className="font-semibold flex items-center gap-2">
          <File className="w-5 h-5 text-purple-400" />
          Document History
        </h3>
        <p className="text-sm text-gray-400 mt-1">
          Previously generated documents for this engagement
        </p>
      </div>

      {error && (
        <div className="p-3 bg-red-900/50 border border-red-800 rounded-lg text-red-200 text-sm">
          {error}
        </div>
      )}

      {documents.length === 0 ? (
        <div className="text-center py-8 text-gray-500">
          <FileText className="w-10 h-10 mx-auto mb-2 opacity-50" />
          <p>No documents generated yet</p>
          <p className="text-sm mt-1">Use the generator above to create documents</p>
        </div>
      ) : (
        <div className="space-y-2">
          {documents.map(doc => (
            <div
              key={doc.id}
              className="flex items-center justify-between p-3 bg-gray-800 rounded-lg"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
                  <FileText className="w-5 h-5 text-blue-400" />
                </div>
                <div>
                  <div className="font-medium text-sm">
                    {DOCUMENT_TYPE_LABELS[doc.document_type] || doc.document_type}
                  </div>
                  <div className="flex items-center gap-3 text-xs text-gray-500 mt-0.5">
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      {new Date(doc.generated_at).toLocaleString()}
                    </span>
                    <span>v{doc.version || 1}</span>
                    {doc.file_size && (
                      <span>{formatFileSize(doc.file_size)}</span>
                    )}
                  </div>
                  {doc.generated_by_name && (
                    <div className="text-xs text-gray-500 mt-0.5">
                      Generated by {doc.generated_by_name}
                    </div>
                  )}
                </div>
              </div>

              <button
                onClick={() => handleDownload(doc)}
                disabled={downloading === doc.id}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded-lg text-sm"
              >
                {downloading === doc.id ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Download className="w-4 h-4" />
                )}
                Download
              </button>
            </div>
          ))}
        </div>
      )}

      {documents.length > 0 && (
        <div className="text-xs text-gray-500 text-center">
          {documents.length} document{documents.length !== 1 ? 's' : ''} generated
        </div>
      )}
    </div>
  );
}
